name: Deploy SaaS Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/thrly8-apix-backend:latest -f backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/thrly8-apix-backend:latest

      - name: Build and push frontend image
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          docker build -t ${{ secrets.DOCKER_USERNAME }}/thrly8-apix-frontend:latest -f frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/thrly8-apix-frontend:latest

      - name: Deploy with docker-compose
        run: |
          docker-compose down
          docker-compose up -d --build
